# Generated by Django 4.2 on 2025-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                default="https://res.cloudinary.com/demo/image/upload/v1690000000/placeholder.png",
                null=True,
                upload_to="services/",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(default="Untitled Service", max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(),
        ),
    ]
