# Generated by Django 4.2 on 2025-10-02 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "service_manager",
            "0002_remove_service_created_at_remove_service_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="available_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
