# Generated by Django 4.2 on 2025-10-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_manager", "0003_service_available_date_service_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="available_date",
        ),
        migrations.RemoveField(
            model_name="service",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="user",
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                default="https://res.cloudinary.com/demo/image/upload/v1690000000/placeholder.png",
                null=True,
                upload_to="services/",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
